### PR TITLE
Adding class comments

### LINKED ISSUE #2: Need a class-doq.
Class documentation (class-doq) likely needs addressing in this first version. It sounds like @k-ericson is working on this. Shouldn't be _too_ difficult to throw something together based on fun-doc and file-doc.

### PR DESCRIPTION
**Pull request by k-ericson**
Starting a pull request for merging this into the main branch

One question - do we want to start writing the comments, then prompt the user, or prompt for everything from the user, and then write it?
* it's currently doing the latter

Also, how do we feel about multiple insert lines vs concatenating stuff?  I've been a bit lazy and falling back on the multiple insert lines - this can be cleaned up!

### CODE REVIEW

**Comment by joshuaguerin** [comment]
@k-ericson With respect to your first question, I have tried to make the others build iteratively. So, if the first three lines can be built automatically, and the fourth line needs input, the current versions (I believe) will build/insert the first three then prompt.

We could always update that behavior when we refactor later, but I think there is merit to the approach. For instance, the user has to concentrate on _only one_ line at a time. Having materials immediately inserted after they are built allows the user to visualize everything the system is saying (and they have already said) without having to do it all from memory or by parsing the prototype.

This behavior is also somewhat consistent with some other functions I have seen. E.g., Have emacs open an empty HTML document and issue `C-c C-t`. When I first proposed this library, that was essentially the behavior I was trying to emulate. And if you have not seen this one before, "you are welcome." :wink:

If you are good with this, do you mind revisiting for some level of consistency?

You'll note that the construction is iterative, prompts are in the order and timing you would expect, and whatever additional minimal information is necessary is printed.

As for multiple inserts vs. concatenation, I wouldn't worry about it right now. I have done some concatenations where necessary or to avoid some inserts with almost no content, so the current base is entirely inconsistent (so use concat` where it feels appropriate, but don't worry too much atm). I'm meaning to handle that in #1 eventually. I'd probably like to ditch interactive in the process to make things more functional and less imperative. The end result may well look something like a concatenation or (possibly more likely, idk) a list being built up and having an insert mapped to it at appropriate intervals.

**Comment by joshuaguerin** [comment]
I took a look at the code as well. I think most of it looks like it tracks so far outside of what we have already discussed.

One thing I would want to point out is that the given regex method of finding the end of a class definition is flawed for a couple of reasons. First, it doesn't account for nested `};`s. (E.g., declaring a struct within a class or something? I think this is plausible syntax.)

The second is that there is no end of line requirement for `};` (i.e., the use of `$`).

I don't think either are necessarily deal-breakers at the moment. Will they even see that particular syntax this semester? If so we will want to fix. (If you are unsure you may want to think a bit about it.) If not, we could just consider it outside of the scope of this particular pull request and drop another issue in place.

**Comment by k-ericson** [comment]
D'oh, forgot about nested classes/structs (I hates them -__-) - I was more thinking of the issue of multiple separate classes in a file...

For 222, we would likely have a struct declared outside the class, then the class itself.  I did want to avoid jumping to the end of the file, to make sure the class documentation was within any header guards.  Do you have a better idea of locating the end of a class?

I'll push once I get the last notes fixed up!

**Comment by joshuaguerin** [comment]
You are welcome to hate them. They don’t really bother me, tho. I like the idea of being able to encapsulate/protect objects/functions/etc. entirely within the scope of the object that uses them (assuming said object is the only place we’ll ever see/use it).

And, no, jumping to the end doesn’t make sense either. No guarantee it would be there (especially if there are header guards) or, in the case of multiple consecutive declarations, no guarantee it will be the correct termination.

A fix could be relatively simple:
- Write a recursive function that scans forward (built in search or perhaps something custom).
- Maintain a counter as a parameter.
- Look for any instances of { or }, increase or decrease the counter accordingly.
- When you it a } and the counter is 0, don’t you have to be at the correct block level?

I think this should take care of any sorts of nesting. Also should just pop into place correctly in the current code.

**Comment by k-ericson** [comment]
I'm doing some digging, I may have a fix for finding the end of the class

**Comment by k-ericson** [comment]
Now with [(forward-sexp)](https://doc.endlessparentheses.com/Fun/forward-sexp) to find the closing curly brace!
does expect the line to end with an open curly brace - would it be safer to do a reverse search from (end-of-line) to find the open?

**Comment by joshuaguerin** [comment]
OK I see what you did there. I guess this is a question of "how do we want this formatted?"

I don't know if there is an agreed upon standard for C++ documentation conventions, even if you restrict your attention to doxygen. I guess the question is do we prefer to see it pre, post, or infix?

Postfix, as written:
```
class myClass {
  int a_member, another_member;
  string second_member;

  float	foo(int bar);
};

/* @class myClass test.cpp "temp/test.cpp"                                      
 * @brief a brief                                                               
 *                                                                              
 * a description                                                                
 */
```

Prefix:
```
/* @class myClass test.cpp "temp/test.cpp"                                      
 * @brief a brief                                                               
 *                                                                              
 * a description                                                                
 */
class myClass {
  int a_member, another_member;
  string second_member;

  float	foo(int bar);
};
```

Infix:
```
class myClass {
/* @class myClass test.cpp "temp/test.cpp"                                      
 * @brief a brief                                                               
 *                                                                              
 * a description                                                                
 */

  int a_member, another_member;
  string second_member;

  float	foo(int bar);
};
````

I personally like postfix the least. It means that you have to scroll to the bottom of the entire structure to actually see docs.

I don't know whether doxygen has a problem parsing infix. I feel like I like either prefix or infix the best.

**Comment by k-ericson** [comment]
Yes, I prefer either pre- or infix, though I now can do postfix happily...
From the doxygen documentation, I thought it needed postfix, but it can likely do either - I can test later!

**Comment by joshuaguerin** [comment]
I'm not tied to either necessarily, but we should try to maintain some consistency. E.g., Function docs with class docs.

I implicitly chose postfix for function, because I thought it looked better:
```
int fun(string a);
/**<                                                                            
 * @param string a A string.                                                    
 * @pre                                                                         
 * @return int The return value.                                                
 * @post                                                                        
 *                                                                              
 * A description.                                                               
 */
```
_Boom_. The name is right there up front. the details follow immediately. It just felt like from a readability standpoint that it made some degree of sense.

I _think_ that would correspond most closely to _infix_. Am I overthinking the level of consistency between the two?

**Comment by joshuaguerin** [comment]
So something does occur to me that may make this decision for us. As per #3, adding Javadoc support could be (somewhat) easy if we maintain consistency. I think that could be fairly doable, and would probably be a nice extension to the project.

If I am to believe [Wiki](https://en.wikipedia.org/wiki/Javadoc#Overview_of_Javadoc), Javadoc is strictly _prefix_.

The basic structure of writing document comments is to embed them inside /** ... */. _The Javadoc comment block is positioned immediately above the items_ without any separating newline. Note that any import statements must precede the class declaration. The class declaration usually contains:

classes:
```
// import statements

/**
 * @author      Firstname Lastname <address @ example.com>
 * @version     1.6                 (current version number of program)
 * @since       1.2          (the version of the package this class was first added to)
 */
public class Test {
    // class body
}
```
methods:
```
/**
 * Short one line description.                           (1)
 * <p>
 * Longer description. If there were any, it would be    (2)
 * here.
 * <p>
 * And even more explanations to follow in consecutive
 * paragraphs separated by HTML paragraph breaks.
 *
 * @param  variable Description text text text.          (3)
 * @return Description text text text.
 */
public int methodName (...) {
    // method body with a return statement
}
```

variables:
```
/**
 * Description of the variable here.
 */
private int debug = 0;
```

If that is the case the will of the crowd may have already spoken for us. If we go with that line of thinking, we could make it a quick modification to _both_ `class-doq` and `fun-doq`.

I don't hate the look of this approach, either.

**Comment by joshuaguerin** [comment]
Looks like we ended up extending the PR a bit more than expected. Going to go ahead and merge now.

**Pull request merged**
