### PR TITLE
Added interactive for @pre, going to set up pull request.

### PR DESCRIPTION
**Pull request by joshuaguerin**
Doing some final minor modifications, features, and testing prior to initial deployment Fall 2021 in Programming II.

### CODE REVIEW

**Comment by joshuaguerin** [comment]
@k-ericson See line 111, insert of @pre. I did it to go ahead and remove an instance of setq (i.e., slightly better convention). Should I run through and get rid of more variables in the same way? (By removing more seq's and calling read where appropriate, anyway?)

Was going to be a part of the clean-up later. Shouldn't take too long to get some of them now.

**Comment by k-ericson** [comment]
Yes, I do like that - if you're in there anyways, doing some cleaning before the big refactor can't hurt!

**Comment by joshuaguerin** [comment]
That will have the added benefit that things will all get requested/printed in the correct order (at least mostly).

**Comment by k-ericson** [comment]
Definitely looking cleaner!

**Comment by joshuaguerin** [comment]
@k-ericson About to go workout. Do you mind stress testing fun-doq?

Things to watch:
- correct behavior, obviously
- pay _really_ close to the order characters are printed as the prompts go out.

I'd like to make sure the flow is good, and that the information displayed at any moment feels appropriate.

I've also gone through and removed any setqs that were just there for user input, and one at the end that was just a decrement. (Didn't get all of them yet, just focusing on those categories for this PR.)

I'll get to the other two when I get back.

**Comment by k-ericson** [comment]
Looking solid!
One question about flow:
should we print @parm to the file before prompting for it in the buffer?  (same for all things prompted for).
So the file has:
` * @param `
While the user is prompted, instead of waiting for the read in to print that - does that make sense?

**Comment by joshuaguerin** [comment]
Let me think on this. I just started saying that on the code side (or the version printed) it was going to be a bit cumbersome, but now I'm starting to think differently.

I'll take a look at it after lunch to see if I like the results after tinkering.

**Comment by joshuaguerin** [comment]
@k-ericson Without getting to your most recent question, would you double check the read/print stuff really closely again between the three types of docs for correctness/consistency?

I _think_ I have them behaving the same.

**Comment by k-ericson** [comment]
Mostly there!

image

Notes: 

- class-doq is missing a newline after the description
- fun-doq has some logic issues - it still claims a single parameter even when there are no arguments
- do we want fun-doq to do that with constructors?

I'm thinking everything is otherwise lining up correctly!

**Comment by joshuaguerin** [comment]
OK, so I fixed the minor error for classes.

The fun-doq one is vexing but I haven't had time to look too deep. If you look at the debugging prints I added it appears that the () case is reporting length 1. Looking at the list that gets printed, it still seems to be 1. I don't think lisp's length should be doing that. There is something I am missing.

For the final one, that makes sense. We didn't consider that particular case. A possible kludge would be to regex or search the original string to see if there is a type listing, then just not print anything (or void).
 
I've got to get out in a sec to get the kids. If you have any time would you mind taking a look?

**Comment by joshuaguerin** [comment]
The list is non-empty when the parameter list is empty. I'm asking if the list is null (it is not). I'm asking if the car of the list is null (it is not). I'm asking if the cdr of the list is null (it is).

It feels like there has to be something wrong with the split-string call. I'm guessing it is putting an empty string in the list.

**Comment by joshuaguerin** [comment]
@k-ericson I left the debugging info there just in case. Can clean up later.

Do you mind stress testing that part? I've tried a number of permutations and it seems to work.

It is also more correct w.r.t. whitespace--I've set it to trim during the split. (Something else that can be thoroughly tested.

As far as I can tell the new version _seems_ to function correctly over a bunch of test cases. (But, of course, another set of eyes could be useful here.)

**Comment by k-ericson** [comment]
Handles extra whitespace well!
Robust enough to handle extra whitespace - will freak out over newlines in the function definition, but that has to do with how we're pulling the line to parse

**Comment by joshuaguerin** [comment]
How are we pulling the prototype to parse? Are we doing it in a way that spans lines? I figured we were just grabbing a single line.

(Edit: switched line -> prototype)

Edit:
I.e., Do you have an example so I also know that I am hearing what you are saying?

**Comment by k-ericson** [comment]
the function prototype is just pulling the immediate line - it would take some extra logic to try to figure out if the statement spans multiple lines...

Here's a quick image:
image

It didn't perform poorly or break, just missed out on the parameters on following lines

**Comment by joshuaguerin** [comment]
First, I may have fixed the constructor issue for now by better parsing the string prior to the first "(". Would you check to see if this works correctly?

As for the issue you just described with an example--yes. Are you saying that this is a bug in general with the way that the string is parsed then, and not an effect of what I've done recently?

If this is the case, you are correct that it needs eventual addressing. (But it may be complicated to do well.) We should open another issue related to just that. I'm thinking that is a fix for another semester.

**Comment by k-ericson** [comment]
For the first one, looking good for constructors (destructors too!)

image

For the issue from the previous example - it's a bug (or at least, poor planning) in the way we're pulling the string to parse, not an effect of what you've done recently (what you've done recently actually handled the accidental empty argument ",    ," I'd put in, so yay!)

I'm thinking you're right with the idea to fix it later - add to the todo list and worry then
(though potentially easier, now that you're looking for the first "("

**Comment by joshuaguerin** [comment]
OK, cool. (Issue created about multi-line prototypes.

I wouldn't call it easier, necessarily. We're going to have to process all the way up to a  `;`, possibly over the course of multiple lines. Not certain how trivial that will be.

Have you tested enough for me to remove debugging stuff for those two issues?

Also, I'm trying to imagine whether we will have to handle nested parenthesis in a prototype. Can you think of a valid use case for that? I know a _call_ can easily have them. I'm not certain whether that's also something we are going to have to deal with.

**Comment by k-ericson** [comment]
good to remove debugging and close this!

nested parens are much more common in Java than C++, but still a potential issue - wait, I'm thinking function call, not prototype
We can use built-in functions to find a matching closing parentheses - that seems like the best approach for such a thing

**Comment by joshuaguerin** [comment]
OK. I removed debugging. Taking a moment to do a little extra clean-up/documentation first. May ask you about one more test run. Since it is fresh on my mind I want to put notes for refactor/improvement later.

**Comment by joshuaguerin** [comment]
OK, I lied. There were a few places to clean and refactor while it was fresh. A few places were bugging me quite a bit, and I think now it will be much easier to understand/work with/refactor later.

(If you look at fun-doq, it should look much cleaner. A bunch was moved into helper functions below it.)

Do you want to do a final check over all of your tests as well? I think it looks like it is still behaving correctly in mine.

**Comment by joshuaguerin** [comment]
If things look good I'll go ahead and merge (for real, for real this time).

**Comment by k-ericson** [comment]
All my tests are running well!

**Comment by joshuaguerin** [comment]
OK. I'm satisfied if you are. After all, you will be doing a test run this semester! 😆 

I'll merge and we'll call it "a day" for now, and consider it ready to go live for the fall.

**Pull request merged**
